### ISSUE TITLE
Question about project enhancements

### ISSUE THREAD

**Issue by Tzal3x** [tiagoboeing/bull-board#6]
Hi, I've been reading the README me file of your project, but I can't find what are the enhancements you have made to the original bull-board. Can you please clarify?

**Comment by tiagoboeing** [comment]
Hello @Tzal3x!

The **enhancements** are related to a way to running using Docker. You can pass the configurations for the container using environment variables.

Another improvement made it's a way to [require a basic authentication](https://github.com/tiagoboeing/bull-board?tab=readme-ov-file#authentication)(https://github.com/tiagoboeing/bull-board/pull/3) before access the dashboard.

Bull board provides some libraries to run using Express or other frameworks, but doesn't provide any official Docker image. This was motivated by a personal needs and I forked for this and kept open-source to support other people.

Keep in mind that this repository uses Bull Board `v4` and the latest version it's the `v5`. I haven't made any changes for a long time, but anyone can support the repository to keep the dependencies up to date and develop more things.

**Comment by Tzal3x** [comment]
Hey @tiagoboeing! Thanks for the quick reply, nice work, it's very useful to know what was the change exactly!

However what I was looking for was an extension that I could extract various statistics and metrics about average job execution time, timestamp percentiles etc. 

Thanks again though, and sorry for my delayed reply!

**Comment by tiagoboeing** [comment]
@Tzal3x I never used this before, but this may be what you are searching for: https://github.com/ron96G/bullmq-exporter

It looks like a way to have the BullBoard dashboard and metrics exposed to use together with Prometheus. This way you can monitor the queues via Grafana or other similar tools.

**Comment by Tzal3x** [comment]
Oh wow, this could be exactly what I'm looking for. I will give this a go for sure. Thank you once again @tiagoboeing 🙏 !
